### PR TITLE
Fix #12: File.keys() and File.__iter__ buggy with escaped keys

### LINKED ISSUE #12: File.__contains__ is slow
It is convenient in Dask to frequently check if a key is present in the `.data` dictionary.  Unfortunately this is slow, due to calls to both `os.path.exists` and `_safe_key`.

### PR DESCRIPTION
**Pull request by pitrou**
Also speed up keys(), `__iter__`, `__len__` and `__contains__` by avoiding filesystem access.

### CODE REVIEW

**Comment by mrocklin** [comment]
Although I suppose it was failing before as well.  Not sure what the right solution is here.

**Comment by pitrou** [comment]
> This would fail if we try to load a pre-existing directory, which I think is generally a reasonable use case.

Do we use that feature, or are there other users of zict?

**Comment by pitrou** [comment]
In any case, it's easy to load the pre-existing directory, so I added code to do that.

**Comment by mrocklin** [comment]
> Do we use that feature, or are there other users of zict?

Nope.  Valid point.

**Comment by mrocklin** [comment]
> In any case, it's easy to load the pre-existing directory, so I added code to do that.

This suffers the same problem we had before, that we can't reverse the `_safe_key` operation.  But given that it was a problem before this is clearly still an improvement :)

**Comment by mrocklin** [comment]
Oh, I see, there is a reversal function to `quote`.

**Pull request merged**
