### PR TITLE
Fix dask cuda worker's race condition failure

### PR DESCRIPTION
**Pull request by pradghos**
- Fixing - https://github.com/rapidsai/dask-cuda/issues/232

- issue is observed during multiple dask cuda worker creation
  and some of the dask-cuda worker died after failing with EEXIST
  error.

### CODE REVIEW

**Comment by pentschev** [comment]
As per @pradghos ' comment in https://github.com/rapidsai/dask-cuda/issues/232#issuecomment-581363035, `os.makedirs` doesn't work in Python 2.7.

@mrocklin is it time to drop Python 2.7 support here too? Dask has already done that for a few months now.

**Comment by pentschev** [comment]
And thanks @pradghos for working on this, I would wait a little for @mrocklin 's reply here to see if we can just drop Python 2 support.

**Comment by pradghos** [comment]
@pentschev : Sure . Thanks for looking ! 

@pentschev @mrocklin : In case we are going to support python 2.7 for some more time. Then below fix should work - I can update the PR based on the decision taken.
```
        try:
            os.mkdir(self.directory)
        except OSError as err:
            if os.path.isdir(self.directory) and err.errno == errno.EEXIST:
                for n in os.listdir(self.directory):
                    self._keys.add(_unsafe_key(n))
            else:
                raise
```

**Comment by jrbourbeau** [comment]
xref https://github.com/dask/zict/pull/34

**Comment by jrbourbeau** [comment]
@pradghos since we dropped support for Python 2.7 in #34, is the change from `mkdir` to `makedirs` still needed?

**Comment by pradghos** [comment]
> 
> 
> @pradghos since we dropped support for Python 2.7 in #34, is the change from `mkdir` to `makedirs` still needed?

Yes this change is still require to fix dask cuda worker's race condition issue. This change will not work  with python 2.7 ; As we have already dropped the support of python 2.7, we are good to go with this change. 
Please let me know in case of any review comments. Thank you !

**Comment by pentschev** [comment]
LGTM, thanks @pradghos for working on this and @jrbourbeau for taking care of dropping Python 2.7!

**Comment by pentschev** [comment]
@jrbourbeau @mrocklin @quasiben is this good to be merged? We have more users having the same issue that is fixed here. For reference: https://github.com/rapidsai/dask-cuda/issues/243

**Comment by jakirkham** [comment]
Thanks @pradghos and @pentschev! 😄

**Comment by pentschev** [comment]
Thanks @jakirkham !

**Comment by jakirkham** [comment]
This is now included in `zict` version `2.0.0`. 🙂

**Pull request merged**
