### PR TITLE
Add code linting and style check

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds `flake8` and `black` checks for linting and code style

### CODE REVIEW

**Comment by jrbourbeau** [comment]
I forgot `black` is only supported on Python 3.6+. So this PR can wait on #34

**Comment by jakirkham** [comment]
Probably also good to merge all other contributor PRs first lest they have to deal with conflicts.

**Comment by jrbourbeau** [comment]
Yeah, totally agree. This PR can wait

**Comment by jakirkham** [comment]
Should we try this again? Seems like PRs that can easily be merged have been.

**Comment by jrbourbeau** [comment]
Thanks for the reminder @jakirkham  : ) I've merged `master` to bring this PR up-to-date and re-run `black`

**Comment by jrbourbeau** [comment]
Planning to merge this later today is no further comments

**Comment by jakirkham** [comment]
Thanks @jrbourbeau! 😄

**Pull request merged**
