### PR TITLE
Add LMDB backend

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by mrocklin** [comment]
We'll need to add lmdb to the travis.ci yml file

**Comment by mrocklin** [comment]
I've moved this repository over to the dask organization

**Comment by pitrou** [comment]
I've submitted a conda-forge recipe for lmdb: https://github.com/conda-forge/staged-recipes/pull/1809.

**Comment by mrocklin** [comment]
Merging this for now (there appear to be a few PRs on top of it).  For what its worth my development practices on this repository have been pretty lazy.  I often push to master.

**Pull request merged**
