### PR TITLE
contains returns false on non-strings

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by pitrou** [comment]
Other methods don't check the type of the key. Is it useful to make an exception for `__contains__`?
(it seems `__getitem__` would happily TypeError)

**Comment by mrocklin** [comment]
I've added type checks to getitem and delitem as well.  Not sure if that's
the best solution to the problem though.

**Comment by pitrou** [comment]
Perhaps it's better to let the TypeError bubble up? Passing non-string keys is a programmer error on our part.

**Comment by mrocklin** [comment]
OK, worked around on the user side.  Closing.

**Pull request closed without merging**
