### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by crusaderky**
- Drop support for Python 3.7
- Automatically call close() on dereferencing
- Add unit tests for update() and close()

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @crusaderky! 

I pushed a small commit to bump `python_requires` in `setup.cfg`, hope you don't mind

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Comment by jrbourbeau** [comment]
No problem! Sorry for the lack of response over in https://github.com/dask/zict/pull/72 -- that had completely dropped off my radar

**Comment by jakirkham** [comment]
All good. Just happy to make the move generally. Support for more interesting things (like pickle protocol 5, shared memory, etc.) get easier with Python 3.8+

**Pull request merged**
