### PR TITLE
Changed default lmdb encoding to utf-8

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by quasiben** [comment]
@pitrou any reason why `latin1` might be preferred ?

**Comment by pitrou** [comment]
No idea. `utf-8` is probably a better idea, except if we want to be able to read databases persisted with the previous encoding.

**Comment by traverseda** [comment]
Of course ASCII strings will remain fine, it's just databases persisted with the previous encoding that use characters outside of the standard ascii range.

Not really a good way to solve that, but at the end of the day `utf-8` is just going to work for most datasets, where as `latin1` will choke up. I first encountered this issue using zict to cache metadata for a bunch of wikipedia articles, and even though I'm using the english wikipedia `latin1` still died part way through ingesting the dataset.

**Comment by traverseda** [comment]
One thing we could do is allow people to pass strings *or* bytes as keys, that way they can specify their own encoding. I still think utf-8 should be the default, but a `bytes` based key would let people use `func` to implement their own encoding.

**Comment by pitrou** [comment]
For the record, I added this with `dask` in mind, not arbitrary use cases, and AFAIR `dask` uses only ASCII keys. So I probably didn't think too much about the encoding.

**Comment by jakirkham** [comment]
Should we go ahead and merge? Seems sensible to me 🙂

**Comment by jakirkham** [comment]
Went ahead and merged it. Hope that is ok 🙂

**Pull request merged**
