### PR TITLE
MNT Migrate to GitHub actions

### PR DESCRIPTION
**Pull request by thomasjpfan**
Resolves https://github.com/dask/zict/issues/39

(Also runs black so the black test passes)

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jacobtomlinson

**Review by jacobtomlinson — APPROVED** [review]
Awesome thanks!

**Comment by jacobtomlinson** [comment]
Provided checks are passing on your fork this should be good to merge.

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Checks look good but we also need to delete the `.travis.yml` file to disable the Travis builds.

**Review by jacobtomlinson — APPROVED** [review]

**Pull request merged**
